language: node_js
node_js:
  - node
script:
  - npm run test
branches:
  only:
    - master
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.12.0
    coveralls < ./coverage/lcov.info
